parameters:

  env(SPOTIFY_CLIENT_ID): ''
  env(SPOTIFY_CLIENT_SECRET): ''

  spotify.session.scopes:
    # Library
    - user-library-read
    - user-library-modify
    # Playlists
    - playlist-read-private
    - playlist-modify-public
    - playlist-modify-private
    - playlist-read-collaborative
    # Listening History
    - user-read-recently-played
    - user-top-read
    # Users
    - user-read-private
    - user-read-email
    - user-read-birthdate
    # Spotify Connect
    - user-modify-playback-state
    - user-read-currently-playing
    - user-read-playback-state
    # Follow
    - user-follow-modify
    - user-follow-read

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Infrastructure\Application\ActionResolver: ~
    App\Infrastructure\Application\HttpApplication: ~

    App\Infrastructure\Actions\:
        resource: '../Actions/'

    # user

    App\Infrastructure\User\UserSessionManager: ~
    App\Infrastructure\User\InitializableUserSessionManager: '@App\Infrastructure\User\UserSessionManager'
    App\Infrastructure\User\InitializedUserSessionManager: '@App\Infrastructure\User\UserSessionManager'

    # spotify

    App\Infrastructure\Spotify\Session\SpotifySessionManager: ~
    App\Infrastructure\Spotify\Session\InitializableSpotifySessionManager: '@App\Infrastructure\Spotify\Session\SpotifySessionManager'
    App\Infrastructure\Spotify\Session\InitializedSpotifySessionManager: '@App\Infrastructure\Spotify\Session\SpotifySessionManager'

    App\Infrastructure\Spotify\Session\SpotifySessionFactory:
      class: App\Infrastructure\Spotify\Session\SpotifySessionFactory
      arguments:
        $clientId: '%env(string:SPOTIFY_CLIENT_ID)%'
        $clientSecret: '%env(string:SPOTIFY_CLIENT_SECRET)%'
        $authorizationScopes: '%spotify.session.scopes%'

    App\Infrastructure\Spotify\Api\SpotifyWebApiFactory: ~

    SpotifyWebAPI\SpotifyWebAPI:
      factory: 'App\Infrastructure\Spotify\Api\SpotifyWebApiFactory:create'

    App\Infrastructure\Spotify\SpotifyUserLibraryFacade: ~
