services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\User\UserSessionManager: ~
    App\User\InitializableUserSessionManager: '@App\User\UserSessionManager'
    App\User\InitializedUserSessionManager: '@App\User\UserSessionManager'
