parameters:

    env(SPOTIFY_CLIENT_ID): ''
    env(SPOTIFY_CLIENT_SECRET): ''

    spotify.session.scopes:
        # Library
        - user-library-read
        - user-library-modify
        # Playlists
        - playlist-read-private
        - playlist-modify-public
        - playlist-modify-private
        - playlist-read-collaborative
        # Listening History
        - user-read-recently-played
        - user-top-read
        # Users
        - user-read-private
        - user-read-email
        - user-read-birthdate
        # Spotify Connect
        - user-modify-playback-state
        - user-read-currently-playing
        - user-read-playback-state
        # Follow
        - user-follow-modify
        - user-follow-read

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Bouda\SpotifyAlbumTagger\User\UserSessionManager: ~
    Bouda\SpotifyAlbumTagger\User\InitializableUserSessionManager: '@Bouda\SpotifyAlbumTagger\User\UserSessionManager'
    Bouda\SpotifyAlbumTagger\User\InitializedUserSessionManager: '@Bouda\SpotifyAlbumTagger\User\UserSessionManager'

    Bouda\SpotifyAlbumTagger\Spotify\Session\SpotifySessionManager: ~
    Bouda\SpotifyAlbumTagger\Spotify\Session\InitializableSpotifySessionManager: '@Bouda\SpotifyAlbumTagger\Spotify\Session\SpotifySessionManager'
    Bouda\SpotifyAlbumTagger\Spotify\Session\InitializedSpotifySessionManager: '@Bouda\SpotifyAlbumTagger\Spotify\Session\SpotifySessionManager'

    Bouda\SpotifyAlbumTagger\Spotify\Session\SpotifySessionFactory:
        class: Bouda\SpotifyAlbumTagger\Spotify\Session\SpotifySessionFactory
        arguments:
            $clientId: '%env(string:SPOTIFY_CLIENT_ID)%'
            $clientSecret: '%env(string:SPOTIFY_CLIENT_SECRET)%'
            $authorizationScopes: '%spotify.session.scopes%'

    Bouda\SpotifyAlbumTagger\Spotify\Api\SpotifyWebApiFactory: ~

    SpotifyWebAPI\SpotifyWebAPI:
        factory: 'Bouda\SpotifyAlbumTagger\Spotify\Api\SpotifyWebApiFactory:create'

    Bouda\SpotifyAlbumTagger\Spotify\SpotifyUserLibraryFacade: ~
