parameters:

    env(SPOTIFY_CLIENT_ID): ''
    env(SPOTIFY_CLIENT_SECRET): ''

services:

    spotifySessionFactory:
        class: Bouda\SpotifyAlbumTagger\Spotify\Session\SpotifySessionFactory
        public: true
        arguments:
            $clientId: '%env(string:SPOTIFY_CLIENT_ID)%'
            $clientSecret: '%env(string:SPOTIFY_CLIENT_SECRET)%'
            $redirectUri: '%wwwUrl%'
