services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Application\ActionResolver: ~
    App\Application\HttpApplication: ~

    App\Actions\:
        resource: '../../actions'

imports:
    - '../Spotify/config.yaml'
    - '../User/config.yaml'
